# ██╗    ██╗ █████╗ ██╗     ██╗     ██╗   ██╗███████╗████████╗
# ██║    ██║██╔══██╗██║     ██║     ██║   ██║██╔════╝╚══██╔══╝
# ██║ █╗ ██║███████║██║     ██║     ██║   ██║███████╗   ██║   
# ██║███╗██║██╔══██║██║     ██║     ██║   ██║╚════██║   ██║   
# ╚███╔███╔╝██║  ██║███████╗███████╗╚██████╔╝███████║   ██║   
#  ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚══════╝   ╚═╝   
# config by furcom (https://github.com/furcom)

# wallust v3.0.*
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml
#
# THIS IS A SAMPLE AND EASY TO COMPREHEND CONFIG, for more info:
#    `man wallust.5` or check the wiki in the repo
#
# You can copy this file to ~/.config/wallust/wallust.toml

# -- global space -- # values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "resized"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lab"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
#check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
#saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A relative path that points to a file where wallust.toml is located, usually at `~/.config/wallust/`.
# target: Absolute path in which to place a file with generated templated values.
# If one is a directory, the other one NEEDS to also be one, one line example below
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }
hyprland.template = "hyprland"
hyprland.target = '~/.config/hypr/configs/colors.conf'
hyprland.new_engine = true

hyprlock.template = "hyprlock"
hyprlock.target = '~/.config/hypr/hyprlock.conf'
hyprlock.new_engine = true

mako.template = "mako"
mako.target = '~/.config/mako/config'
mako.new_engine = true

waybar.template = "waybar"
waybar.target = '~/.config/waybar/colors.css'
waybar.new_engine = true

rofi.template = "rofi"
rofi.target = '~/.config/rofi/colors.rasi'
rofi.new_engine = true

kitty.template = "kitty"
kitty.target = '~/.config/kitty/style.conf'
kitty.new_engine = true

sddm.template = "sddm"
sddm.target = '/usr/share/sddm/themes/fyprland/Main.qml'
sddm.new_engine = true

sddm-2.template = "sddm-2"
sddm-2.target = '/usr/share/sddm/themes/fyprland/SimpleControls/SimpleComboBox.qml'
sddm-2.new_engine = true

wlogout.template = "wlogout"
wlogout.target = '~/.config/wlogout/style.css'
wlogout.new_engine = true
