#!/bin/bash
#  ██████╗██╗   ██╗██████╗ ███████╗ ██████╗ ██████╗
# ██╔════╝██║   ██║██╔══██╗██╔════╝██╔═══██╗██╔══██╗
# ██║     ██║   ██║██████╔╝███████╗██║   ██║██████╔╝
# ██║     ██║   ██║██╔══██╗╚════██║██║   ██║██╔══██╗
# ╚██████╗╚██████╔╝██║  ██║███████║╚██████╔╝██║  ██║
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝
# script by furcom (https://github.com/furcom)

source $HOME/.config/hypr/scripts/HYPR_VARS

# Set the directory where the cursors are located
directory=$HOME/.icons

# Check if the directory exists
if [ -d "$directory" ]; then
    while true; do
        clear
        # Create an array of all the folders (cursors) in the directory
        cursors=($(ls -d $directory/*/))

        # Display a menu of cursor folders
        echo -e "${CYAN}\n ██████╗██╗   ██╗██████╗ ███████╗ ██████╗ ██████╗"
        echo -e "██╔════╝██║   ██║██╔══██╗██╔════╝██╔═══██╗██╔══██╗"
        echo -e "██║     ██║   ██║██████╔╝███████╗██║   ██║██████╔╝"
        echo -e "██║     ██║   ██║██╔══██╗╚════██║██║   ██║██╔══██╗"
        echo -e "╚██████╗╚██████╔╝██║  ██║███████║╚██████╔╝██║  ██║"
        echo -e " ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝${NC}\n"
        for i in "${!cursors[@]}"; do
            # Show only the folder name without the full path
            echo "$((i+1)). $(basename ${cursors[$i]})"
        done

        # Read the user choice
        echo ""
        read -p "Enter your choice or press 'ENTER' to return to exit: " choice

        # Handle empty input (Enter pressed)
        if [[ -z "$choice" ]]; then
            exit 0
        fi

        # Check if the choice is valid
        if (( choice > 0 && choice <= ${#cursors[@]} )); then
            selected_cursor=$(basename "${cursors[$((choice-1))]}")

            # Ask for cursor size
            echo -e "\n"
            read -p "Enter cursor size (1-512): " cursor_size

            # Validate cursor size
            if (( cursor_size >= 1 && cursor_size <= 512 )); then
                # Set the cursor using hyprctl
                hyprctl setcursor "$selected_cursor" "$cursor_size" > /dev/null
                echo -e "\nCursor theme set to:$GREEN $selected_cursor ${NC}with size:$GREEN ${cursor_size}$NC\n"
                read -n1 -p "Press any key to return to the cursor menu..."
            else
                echo -e "$RED\nInvalid cursor size. Must be a number between 1 and 512.\n$NC"
                read -n1 -p "Press any key to return to the cursor menu..."
            fi
        else
            echo -e "$RED\n\nInvalid choice.$NC\n"
            read -n1 -p "Press any key to continue..."
        fi
    done
else
    echo -e "\nDirectory $directory does not exist.\n"
    exit 1
fi
