#!/bin/bash
#  ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███╗   ██╗███████╗███████╗███████╗
#  ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝████╗  ██║██╔════╝██╔════╝██╔════╝
#  ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ██╔██╗ ██║█████╗  ███████╗███████╗
#  ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ██║╚██╗██║██╔══╝  ╚════██║╚════██║
#  ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ██║ ╚████║███████╗███████║███████║
#  ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝╚══════╝╚══════╝
# script by furcom (https://github.com/furcom)
notify() {
    max_brightness=$(brightnessctl max)
    current_brightness=$(brightnessctl get)
    percentage=$(( 100 * current_brightness / max_brightness ))
    if [ "$percentage" -ge 75 ]; then
        pkill mako
        notify-send "󰃠  $percentage%"
    elif [ "$percentage" -ge 50 ]; then
        pkill mako
        notify-send "󰃝  $percentage%"
    elif [ "$percentage" -ge 25 ]; then
        pkill mako
        notify-send "󰃟  $percentage%"
    elif [ "$percentage" -ge 10 ]; then
        pkill mako
        notify-send "󰃛  $percentage%"
    else
        pkill mako
        notify-send "󰃚  $percentage%"
    fi
}

case "$1" in
    --inc) brightnessctl s 10%+ && notify ;;
    --dec) brightnessctl s 10%- && notify ;;
    --max) brightnessctl s 100% && notify ;;
    --mid) brightnessctl s 50% && notify ;;
    --notify) notify ;;
esac
