#!/bin/bash
max_brightness=$(brightnessctl max)
current_brightness=$(brightnessctl get)
percentage=$(( 100 * current_brightness / max_brightness ))
if [ "$percentage" -ge 75 ]; then
    pkill mako
    notify-send "󰃠  $percentage%"
elif [ "$percentage" -ge 50 ]; then
    pkill mako
    notify-send "󰃝  $percentage%"
elif [ "$percentage" -ge 25 ]; then
    pkill mako
    notify-send "󰃟  $percentage%"
elif [ "$percentage" -ge 10 ]; then
    pkill mako
    notify-send "󰃛  $percentage%"
else
    pkill mako
    notify-send "󰃚  $percentage%"
fi
