#!/bin/bash
# ██╗   ██╗ █████╗ ██████╗ ██╗ █████╗ ██████╗ ██╗     ███████╗███████╗
# ██║   ██║██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
# ██║   ██║███████║██████╔╝██║███████║██████╔╝██║     █████╗  ███████╗
# ╚██╗ ██╔╝██╔══██║██╔══██╗██║██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
#  ╚████╔╝ ██║  ██║██║  ██║██║██║  ██║██████╔╝███████╗███████╗███████║
#   ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝
# by furcom (https://github.com/furcom)

############
# PROGRAMS #
############

EDITOR="vim"
TERMINAL="kitty"
AUR_HELPER="yay"
WG_CONFIG="/etc/wireguard/wg0.conf"

###############
# Directories #
###############

# General
CFGDIR="$HOME/.config"
CacheDir="$HOME/.cache"

# fusuma
FusumaDir="$HOME/.config/fusuma"
FusumaScriptsDir="$FusumaDir/scripts"

# Hypr Ecosystem
HyprDir="$HOME/.config/hypr"
HyprScriptsDir="$HyprDir/scripts"
HyprConfigsDir="$HyprDir/configs"

HyprImagesDir="$HyprDir/images/"
HyprWallpapersDir="$HyprImagesDir/wallpapers"

# kitty
KittyDir="$HOME/.config/kitty"
KittyConfigsDir="$KittyDir/configs"

# rofi
RofiDir="$HOME/.config/rofi"
RofiScriptsDir="$RofiDir/scripts"
RofiMenu="rofi -dmenu -config $RofiDir/config.rasi"
RofiMenuSettings="rofi -dmenu -config $RofiDir/settings.rasi"

# waybar
WaybarDir="$HOME/.config/waybar"
WaybarScriptsDir="$WaybarDir/scripts"

# wallust
WallustDir="$HOME/.config/wallust"
WallustTemplatesDir="$WallustDir/templates"

# mako
MakoDir="$HOME/.config/mako"

##########
# COLORS #
##########

NC='\033[0m'
RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
CYAN='\e[36m'
MAGENTA='\e[35m'
YELOW='\e[33m'
