#!/bin/bash
# ██╗  ██╗███████╗██╗   ██╗██████╗  ██████╗  █████╗ ██████╗ ██████╗    
# ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔══██╗   
# █████╔╝ █████╗   ╚████╔╝ ██████╔╝██║   ██║███████║██████╔╝██║  ██║   
# ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔══██╗██║   ██║██╔══██║██╔══██╗██║  ██║   
# ██║  ██╗███████╗   ██║   ██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝   
# ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝    
# ██████╗  █████╗  ██████╗██╗  ██╗██╗     ██╗ ██████╗ ██╗  ██╗████████╗
# ██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██║     ██║██╔════╝ ██║  ██║╚══██╔══╝
# ██████╔╝███████║██║     █████╔╝ ██║     ██║██║  ███╗███████║   ██║   
# ██╔══██╗██╔══██║██║     ██╔═██╗ ██║     ██║██║   ██║██╔══██║   ██║   
# ██████╔╝██║  ██║╚██████╗██║  ██╗███████╗██║╚██████╔╝██║  ██║   ██║   
# ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   
                                                                     
notify_user() {
    brightness=$(brightnessctl -d 'tpacpi::kbd_backlight' g)
    if [[ "$brightness" == "0" ]]; then
        pkill mako
        notify-send "󰃞 󰌌  Off"
    elif [[ "$brightness" == "1" ]]; then
        pkill mako
        notify-send "󰃟 󰌌  50%"
    elif [[ "$brightness" == "2" ]]; then
        pkill mako
        notify-send "󰃠 󰌌  100%"
    fi
}

if [[ "$1" == "--get" ]]; then
    brightnessctl -d 'tpacpi::kbd_backlight' g
elif [[ "$1" == "--inc" ]]; then
    brightnessctl -d 'tpacpi::kbd_backlight' set 50%+ && notify_user
elif [[ "$1" == "--dec" ]]; then
    brightnessctl -d 'tpacpi::kbd_backlight' set 50%- && notify_user
elif [[ "$1" == "--zero" ]]; then
    brightnessctl -d 'tpacpi::kbd_backlight' set 0% && notify_user
elif [[ "$1" == "--full" ]]; then
    brightnessctl -d 'tpacpi::kbd_backlight' set 100% && notify_user
else
    brightnessctl -d 'tpacpi::kbd_backlight' g
fi
