#!/bin/bash
# ██╗      █████╗ ██╗   ██╗ ██████╗ ██╗   ██╗████████╗███████╗
# ██║     ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║╚══██╔══╝██╔════╝
# ██║     ███████║ ╚████╔╝ ██║   ██║██║   ██║   ██║   ███████╗
# ██║     ██╔══██║  ╚██╔╝  ██║   ██║██║   ██║   ██║   ╚════██║
# ███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝   ██║   ███████║
# ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝
# script by furcom (https://github.com/furcom)

config_file="$HOME/.config/hypr/configs/general.conf"

if [[ -f "$config_file" ]]; then
    case "$1" in
        --master)
            sed -i '/^[[:space:]]*layout =/c\    layout = master' "$config_file"
            ;;
        --dwindle)
            sed -i '/^[[:space:]]*layout =/c\    layout = dwindle' "$config_file"
            ;;
    esac
fi
