#!/bin/bash
# ██████╗ ██╗██████╗ ███████╗██╗    ██╗██╗██████╗ ███████╗
# ██╔══██╗██║██╔══██╗██╔════╝██║    ██║██║██╔══██╗██╔════╝
# ██████╔╝██║██████╔╝█████╗  ██║ █╗ ██║██║██████╔╝█████╗  
# ██╔═══╝ ██║██╔═══╝ ██╔══╝  ██║███╗██║██║██╔══██╗██╔══╝  
# ██║     ██║██║     ███████╗╚███╔███╔╝██║██║  ██║███████╗
# ╚═╝     ╚═╝╚═╝     ╚══════╝ ╚══╝╚══╝ ╚═╝╚═╝  ╚═╝╚══════╝
# script by furcom (https://github.com/furcom)

# Get volume and save as decimal
mic_volume_info=$(wpctl get-volume @DEFAULT_SOURCE@)

output_icon() {
    if [[ $mic_volume_info == *"MUTED"* ]]; then
        echo ""
        exit 0
    fi
    
    mic_volume=$(echo "$mic_volume_info" | sed 's/Volume: //' | awk '{print $1}')
    mic_volume_percent=$(echo "$mic_volume * 100" | bc -l | awk '{printf "%.0f", $0}')
    
    if [[ $mic_volume_percent -le 100 && $mic_volume_percent -gt 0 ]]; then
        echo ""
    else
        echo ""
    fi
}

output_text() {
    if [[ $mic_volume_info == *"MUTED"* ]]; then
        echo "  Muted"
        exit 0
    fi
    
    mic_volume=$(echo "$mic_volume_info" | sed 's/Volume: //' | awk '{print $1}')
    mic_volume_percent=$(echo "$mic_volume * 100" | bc -l | awk '{printf "%.0f", $0}')
    
    if [[ $mic_volume_percent -le 100 && $mic_volume_percent -gt 0 ]]; then
        echo "  $mic_volume_percent%"
    else
        echo "  Muted"
    fi
}

case "$1" in
    --icon) output_icon ;;
    --text) output_text ;;
esac
