#!/bin/bash
# ███████╗██████╗  ██████╗ ████████╗██╗███████╗██╗   ██╗
# ██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║██╔════╝╚██╗ ██╔╝
# ███████╗██████╔╝██║   ██║   ██║   ██║█████╗   ╚████╔╝ 
# ╚════██║██╔═══╝ ██║   ██║   ██║   ██║██╔══╝    ╚██╔╝  
# ███████║██║     ╚██████╔╝   ██║   ██║██║        ██║   
# ╚══════╝╚═╝      ╚═════╝    ╚═╝   ╚═╝╚═╝        ╚═╝
# scripty by furcom (https://github.com/furcom)

source $HOME/.config/hypr/scripts/HYPR_VARS

    status=$(playerctl -p spotify status)
    artist=$(playerctl -p spotify metadata xesam:artist)
    title=$(playerctl -p spotify metadata xesam:title)
    case $status in
        "Playing" ) echo "  $artist - $title" ;;
        "Paused" ) echo "  $artist - $title" ;;
        * ) echo "" ;;
    esac
