#!/bin/bash

source $HOME/.config/hypr/scripts/HYPR_VARS

wlan_menu() {
    while true; do
        INTERFACE="wlan0"  # Change this to your WiFi adapter
        STATUS=$(nmcli radio wifi)
        CONNECTED=$(nmcli -t -f DEVICE,STATE dev status | grep "$INTERFACE" | awk '{print $2}')
        OPTIONS=""

        if [ "$STATUS" = "enabled" ]; then
            OPTIONS="󰖪 Disable"  # Change "Enable" to "Disable", if WiFi is enabled
            if [ "$CONNECTED" = "connected" ]; then
                OPTIONS="$OPTIONS\n󱘖 Connect\n Disconnect"
            fi
            OPTIONS="$OPTIONS\n󰍉 Scan\n Saved"
        else
            OPTIONS=" Enable"  # Only show wenn WiFi is disabled
        fi
        OPTIONS="󰌍 Back\n$OPTIONS"

        CHOICE=$(echo -e "$OPTIONS" | $RofiMenuAlt -p "WLAN Menu" -selected-row $SelectedRowWifi)

        if [ $? -ne 0 ]; then
            break
        fi

        case "$CHOICE" in
            " Enable")
                nmcli radio wifi on
                break ;;
            "󰖪 Disable")
                nmcli radio wifi off
                break ;;
            "󱘖 Connect")
                connect_to_network ;;
            "󰍉 Scan")
                scan_for_networks ;;
            " Saved")
                manage_saved_networks ;;
            "󰌍 Back")
		$HyprScriptsDir/settings --wifi
		break ;;
            *)
                echo "Invalid choice" ;;
        esac
    done
}

scan_for_networks() {
    while true; do
        nmcli -f SSID device wifi rescan  # Scan for networks
        AVAILABLE_NETWORKS=$(nmcli -f SSID device wifi | tail -n +2 | sed 's/^\s*//;s/\s*$//' | sort -u | sed 's/^--$/<unknown>/')  # Rename "--" to <unknown> and remove duplicate SSIDs

        if [ -z "$AVAILABLE_NETWORKS" ]; then
            SelectedRowWifi="2"
            echo "No networks found" | $RofiMenuAlt
            return
        fi

        SSID=$(echo -e "󰌍 Back\n$AVAILABLE_NETWORKS" | $RofiMenuAlt -p "Select a network:")

        if [ $? -ne 0 ] || [ "$SSID" = "󰌍 Back" ]; then
            SelectedRowWifi="2"
	    break
        fi

        if [ -n "$SSID" ]; then
            SelectedRowWifi="2"
            connect_to_selected_network "$SSID"
            break  # Close menu after connecting
        fi
    done
}

connect_to_selected_network() {
    local SSID=$1

    # Check if network is already saved
    if nmcli -f NAME connection show | grep -q "$SSID"; then
        nmcli device wifi connect "$SSID"
    else
        kitty sh -c "echo 'Please enter the password for $SSID:' && read -s PASSWORD && nmcli device wifi connect '$SSID' password '$PASSWORD'"
    fi
}

manage_saved_networks() {
    while true; do
        SAVED_NETWORKS=$(nmcli connection show | grep -i wifi | awk '{print $1}')

        if [ -z "$SAVED_NETWORKS" ]; then
            SelectedRowWifi="3"
            echo "No saved networks found" | $RofiMenuAlt
            return
        fi

        NETWORK=$(echo -e "󰌍 Back\n$SAVED_NETWORKS" | $RofiMenuAlt -p "Select a network to edit:")

        if [ $? -ne 0 ] || [ "$NETWORK" = "󰌍 Back" ]; then
            SelectedRowWifi="3"
            break
        fi

        ACTION=$(echo -e "󰌍 Back\n󱘖 Connect\n󰆴 Delete" | $RofiMenuAlt -p "Actions for $NETWORK:")

        if [ "$ACTION" = "󰆴 Delete" ]; then
            CONFIRM=$(echo -e "󰄴 Yes\n No" | $RofiMenuAlt -p "Are you sure you want to delete $NETWORK?")
            if [ "$CONFIRM" = "󰄴 Yes" ]; then
                nmcli connection delete "$NETWORK"
                echo "$NETWORK deleted successfully" | $RofiMenuAlt
            fi
        elif [ "$ACTION" = "󱘖 Connect" ]; then
            nmcli device wifi connect "$NETWORK"  # Connect with selected network
            break  # Close menu after connecting
        fi
    done
}

wlan_menu
