#!/bin/bash
#  ██╗    ██╗██╗███████╗██╗
#  ██║    ██║██║██╔════╝██║
#  ██║ █╗ ██║██║█████╗  ██║
#  ██║███╗██║██║██╔══╝  ██║
#  ╚███╔███╔╝██║██║     ██║
#   ╚══╝╚══╝ ╚═╝╚═╝     ╚═╝
# script by furcom (https://github.com/furcom)

NWSTAT=$(nmcli networking connectivity check)
if [ "$NWSTAT" == "none" ];
  then
    nmcli networking on;
    pkill mako
    notify-send "  WiFi On"
  else
    nmcli networking off;
    pkill mako
    notify-send "󰖪  WiFi Off"
fi

